# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Test performance of public S1 servers (native access)
on: [push, pull_request]
# Declare default permissions as read only.
permissions: read-all
jobs:
  pilot_repo_native:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        APPLICATION:
        - TensorFlow
    steps:
        - name: Check out repository
          uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
          with:
            persist-credentials: false

        - name: Mount EESSI CernVM-FS pilot repository
          uses: cvmfs-contrib/github-action-cvmfs@d4641d0d591c9a5c3be23835ced2fb648b44c04b # v3.1
          with:
              cvmfs_config_package: https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi_latest_all.deb
              cvmfs_http_proxy: DIRECT
              cvmfs_repositories: pilot.eessi-hpc.org

        - name: Run public S1 performance test
          run: |
              APPLICATION=${{matrix.APPLICATION}} ./scripts/test_S1_performance.sh
